In [1]:
import sys
sys.path.append("..")

from hnrs.preprocessing import load_preprocessed_mnist

x_train, y_train, y_cat_train, x_test, y_test, y_cat_test = load_preprocessed_mnist()

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline
import keras
from keras import Input
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from sklearn.metrics import confusion_matrix

In [3]:
#x_train = x_train.reshape(x_train.shape[0], -1)
#x_test = x_test.reshape(x_test.shape[0], -1)
#print(x_train.shape, x_test.shape)

In [4]:
keras.utils.set_random_seed(42)
model = Sequential()

model.add(Input(shape=(28,28)))
model.add(Flatten())
model.add(Dense(units=128, activation='relu'))
model.add(Dense(units=64, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(units=10, activation='softmax'))
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten (Flatten)               │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │       100,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 109,386 (427.29 KB)

 Trainable params: 109,386 (427.29 KB)

 Non-trainable params: 0 (0.00 B)

In [5]:
batch_size = 256
epochs = 10
model.fit(x=x_train, y=y_cat_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/10
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8343 - loss: 0.5629 - val_accuracy: 0.9374 - val_loss: 0.2166
Epoch 2/10
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9363 - loss: 0.2218 - val_accuracy: 0.9551 - val_loss: 0.1526
Epoch 3/10
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9539 - loss: 0.1594 - val_accuracy: 0.9625 - val_loss: 0.1256
Epoch 4/10
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9634 - loss: 0.1264 - val_accuracy: 0.9673 - val_loss: 0.1108
Epoch 5/10
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9700 - loss: 0.1033 - val_accuracy: 0.9694 - val_loss: 0.1022
Epoch 6/10
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9746 - loss: 0.0858 - val_accuracy: 0.9719 - val_loss: 0.0933
Epoch 7/10
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9787 - loss: 0.0711 - val_accuracy: 0.9731 - val_loss: 0.0919
Epoch 8/10
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9817 - loss: 0.0614 - val_accuracy: 0.

In [6]:
test_loss, test_acc = model.evaluate(x_test, y_cat_test)
print("Test Loss: {}, Test Accuracy: {}".format(test_loss, test_acc))

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 767us/step - accuracy: 0.9757 - loss: 0.0817
Test Loss: 0.08169787377119064, Test Accuracy: 0.9757000207901001


In [7]:
y_pred = model.predict(x_test).argmax(axis=1)
print(confusion_matrix(y_test, y_pred))

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 613us/step
[[ 973    1    1    0    0    1    2    0    1    1]
 [   0 1125    4    1    0    1    2    0    2    0]
 [   8    0  998    3    1    0    4   10    8    0]
 [   0    0    3  989    0    5    0    6    3    4]
 [   1    1    4    0  960    1    5    1    2    7]
 [   4    0    0    6    1  872    6    1    2    0]
 [   9    3    0    0    4    3  936    0    3    0]
 [   1    3   10    4    1    0    0 1001    0    8]
 [   7    0    1    7    5    7    5    4  933    5]
 [   3    3    0    6   15    5    0    7    0  970]]


In [8]:
model.save("../models/dense.keras")